version: '3'
services:
  db:
    container_name: db
    image: postgres:latest
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - darall
    environment:
      POSTGRES_USER: 'fox'
      POSTGRES_PASSWORD: '123'
      POSTGRES_DB: 'darall'

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    restart: always
#    ports:
#      - "5050:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: 7info7web@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    networks:
#      - darall
#    depends_on:
#      - db

networks:
  darall:

volumes:
  pgadmin: